export const formulas = [
  { formula: "Li₂O", answers: ["Óxido de litio", "Óxido de dilitio"] },
  { formula: "Na₂O", answers: ["Óxido de sodio", "Óxido de disodio"] },
  { formula: "K₂O", answers: ["Óxido de potasio", "Óxido de dipotasio"] },
  { formula: "Rb₂O", answers: ["Óxido de rubidio", "Óxido de dirubidio"] },
  { formula: "Cs₂O", answers: ["Óxido de cesio", "Óxido de dicesio"] },

  { formula: "BeO", answers: ["Óxido de berilio"] },
  { formula: "MgO", answers: ["Óxido de magnesio"] },
  { formula: "CaO", answers: ["Óxido de calcio"] },
  { formula: "SrO", answers: ["Óxido de estroncio"] },
  { formula: "BaO", answers: ["Óxido de bario"] },

  {
    formula: "Al₂O₃",
    answers: ["Óxido de aluminio", "Trióxido de dialuminio"],
  },
  { formula: "Ga₂O₃", answers: ["Óxido de galio"] },
  { formula: "In₂O₃", answers: ["Óxido de indio"] },
  { formula: "Tl₂O", answers: ["Óxido de talio"] },
  { formula: "SnO", answers: ["Óxido de estaño"] },
  { formula: "SnO₂", answers: ["Dióxido de estaño"] },
  { formula: "PbO", answers: ["Óxido de plomo"] },
  { formula: "PbO₂", answers: ["Dióxido de plomo"] },
  { formula: "Bi₂O₃", answers: ["Óxido de bismuto"] },

  { formula: "B₂O₃", answers: ["Óxido de boro", "Trióxido de diboro"] },
  { formula: "SiO₂", answers: ["Dióxido de silicio"] },
  { formula: "GeO₂", answers: ["Dióxido de germanio"] },
  { formula: "As₂O₃", answers: ["Óxido de arsénico"] },
  { formula: "Sb₂O₅", answers: ["Pentaóxido de diantimonio"] },
  { formula: "TeO₂", answers: ["Dióxido de telurio"] },

  { formula: "CO", answers: ["Monóxido de carbono"] },
  { formula: "CO₂", answers: ["Dióxido de carbono"] },
  { formula: "N₂O", answers: ["Óxido de dinitrógeno"] },
  { formula: "NO", answers: ["Monóxido de nitrógeno"] },
  { formula: "NO₂", answers: ["Dióxido de nitrógeno"] },
  { formula: "N₂O₃", answers: ["Trióxido de dinitrógeno"] },
  { formula: "N₂O₅", answers: ["Pentaóxido de dinitrógeno"] },
  { formula: "P₂O₃", answers: ["Trióxido de difósforo"] },
  { formula: "P₂O₅", answers: ["Pentaóxido de difósforo"] },
  { formula: "SO₂", answers: ["Dióxido de azufre"] },
  { formula: "SO₃", answers: ["Trióxido de azufre"] },
  { formula: "S₂O₆", answers: ["Hexaóxido de diazufre"] },
  { formula: "SeO₂", answers: ["Dióxido de selenio"] },

  { formula: "Cl₂O", answers: ["Monóxido de dicloro"] },
  { formula: "Cl₂O₃", answers: ["Trióxido de dicloro"] },
  { formula: "Cl₂O₅", answers: ["Pentaóxido de dicloro"] },
  { formula: "Cl₂O₇", answers: ["Heptaóxido de dicloro"] },

  { formula: "Br₂O", answers: ["Monóxido de dibromo"] },
  { formula: "Br₂O₅", answers: ["Pentaóxido de dibromo"] },

  { formula: "I₂O₅", answers: ["Pentaóxido de diyodo"] },
  { formula: "I₂O₇", answers: ["Heptaóxido de diyodo"] },

  { formula: "XeO₃", answers: ["Trióxido de xenón"] },
  { formula: "XeO₄", answers: ["Tetraóxido de xenón"] },

  { formula: "CrO", answers: ["Óxido de cromo"] },
  { formula: "Cr₂O₃", answers: ["Óxido de cromo (III)"] },
  { formula: "CrO₃", answers: ["Trióxido de cromo"] },

  { formula: "MnO", answers: ["Óxido de manganeso"] },
  { formula: "Mn₂O₃", answers: ["Óxido de manganeso (III)"] },
  { formula: "MnO₂", answers: ["Dióxido de manganeso"] },
  { formula: "Mn₂O₇", answers: ["Heptaóxido de dimanganeso"] },

  { formula: "FeO", answers: ["Óxido de hierro"] },
  { formula: "Fe₂O₃", answers: ["Óxido de hierro (III)"] },
  { formula: "Fe₃O₄", answers: ["Tetraóxido de trihierro"] },

  { formula: "CoO", answers: ["Óxido de cobalto"] },
  { formula: "Co₂O₃", answers: ["Óxido de cobalto (III)"] },

  { formula: "NiO", answers: ["Óxido de níquel"] },
  { formula: "Ni₂O₃", answers: ["Óxido de níquel (III)"] },

  { formula: "PdO", answers: ["Óxido de paladio"] },
  { formula: "PdO₂", answers: ["Dióxido de paladio"] },

  { formula: "PtO", answers: ["Óxido de platino"] },
  { formula: "PtO₂", answers: ["Dióxido de platino"] },

  { formula: "Cu₂O", answers: ["Óxido de cobre (I)"] },
  { formula: "CuO", answers: ["Óxido de cobre (II)"] },

  { formula: "Ag₂O", answers: ["Óxido de plata"] },

  { formula: "Au₂O₃", answers: ["Óxido de oro (III)"] },
  { formula: "Au₂O", answers: ["Óxido de oro (I)"] },

  { formula: "ZnO", answers: ["Óxido de zinc"] },
  { formula: "CdO", answers: ["Óxido de cadmio"] },
  { formula: "HgO", answers: ["Óxido de mercurio"] },
  { formula: "Hg₂O", answers: ["Óxido de dimercurio"] },

  { formula: "Dióxido de carbono", answers: ["CO₂"] },
  { formula: "Trióxido de azufre", answers: ["SO₃"] },
  { formula: "Óxido de hierro (III)", answers: ["Fe₂O₃"] },
  { formula: "Dióxido de manganeso", answers: ["MnO₂"] },
  { formula: "Óxido de cobre (II)", answers: ["CuO"] },
  { formula: "Pentaóxido de difósforo", answers: ["P₂O₅"] },
  { formula: "Trióxido de dicloro", answers: ["Cl₂O₃"] },
  { formula: "Óxido de sodio", answers: ["Na₂O"] },
  { formula: "Óxido de calcio", answers: ["CaO"] },
  { formula: "Dióxido de silicio", answers: ["SiO₂"] },
  { formula: "Óxido de zinc", answers: ["ZnO"] },
  { formula: "Heptaóxido de dicloro", answers: ["Cl₂O₇"] },
  { formula: "Trióxido de xenón", answers: ["XeO₃"] },
  { formula: "Óxido de níquel", answers: ["NiO"] },
  { formula: "Óxido de cobalto", answers: ["CoO"] },
  { formula: "Tetraóxido de trihierro", answers: ["Fe₃O₄"] },
  { formula: "Óxido de plata", answers: ["Ag₂O"] },
  { formula: "Dióxido de telurio", answers: ["TeO₂"] },
  { formula: "Monóxido de nitrógeno", answers: ["NO"] },
  { formula: "Dióxido de nitrógeno", answers: ["NO₂"] },
  { formula: "Óxido de mercurio", answers: ["HgO"] },
  { formula: "Óxido de aluminio", answers: ["Al₂O₃"] },
  { formula: "Óxido de oro (III)", answers: ["Au₂O₃"] },
  { formula: "Dióxido de platino", answers: ["PtO₂"] },
  { formula: "Trióxido de cromo", answers: ["CrO₃"] },
  { formula: "Óxido de litio", answers: ["Li₂O"] },
  { formula: "Óxido de magnesio", answers: ["MgO"] },
  { formula: "Pentaóxido de diantimonio", answers: ["Sb₂O₅"] },
  { formula: "Dióxido de estaño", answers: ["SnO₂"] },
  { formula: "Heptaóxido de diyodo", answers: ["I₂O₇"] },
];
